description: ''
properties:
  enabled:
    description: Whether the embedded component is enabled.
    type: boolean
  features:
    $ref: ./connect_embedded_payments_features.yaml
required:
  - enabled
  - features
title: ConnectEmbeddedPaymentsConfigClaim
type: object
x-expandableFields:
  - features
