description: ''
properties:
  enabled:
    description: Whether the embedded component is enabled.
    type: boolean
  features:
    $ref: ./connect_embedded_base_features.yaml
required:
  - enabled
  - features
title: ConnectEmbeddedBaseConfigClaim
type: object
x-expandableFields:
  - features
