description: ''
properties:
  account_tax_ids:
    description: The account tax IDs associated with the invoice.
    items:
      anyOf:
        - maxLength: 5000
          type: string
        - $ref: ./tax_id.yaml
        - $ref: ./deleted_tax_id.yaml
      x-expansionResources:
        oneOf:
          - $ref: ./tax_id.yaml
          - $ref: ./deleted_tax_id.yaml
    nullable: true
    type: array
  custom_fields:
    description: A list of up to 4 custom fields to be displayed on the invoice.
    items:
      $ref: ./invoice_setting_custom_field.yaml
    nullable: true
    type: array
  description:
    description: >-
      An arbitrary string attached to the object. Often useful for displaying to
      users.
    maxLength: 5000
    nullable: true
    type: string
  footer:
    description: Footer to be displayed on the invoice.
    maxLength: 5000
    nullable: true
    type: string
  issuer:
    anyOf:
      - $ref: ./connect_account_reference.yaml
    description: >-
      The connected account that issues the invoice. The invoice is presented
      with the branding and support information of the specified account.
    nullable: true
  metadata:
    additionalProperties:
      maxLength: 500
      type: string
    description: >-
      Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you
      can attach to an object. This can be useful for storing additional
      information about the object in a structured format.
    nullable: true
    type: object
  rendering_options:
    anyOf:
      - $ref: ./invoice_setting_checkout_rendering_options.yaml
    description: Options for invoice PDF rendering.
    nullable: true
title: PaymentLinksResourceInvoiceSettings
type: object
x-expandableFields:
  - account_tax_ids
  - custom_fields
  - issuer
  - rendering_options
