description: Represents a per-setup override of a reader configuration
properties:
  enable_customer_cancellation:
    description: Enable customer-initiated cancellation when processing this SetupIntent.
    type: boolean
title: TerminalReaderReaderResourceProcessSetupConfig
type: object
x-expandableFields: []
