description: ''
properties:
  ca_certificate_file:
    description: A File ID representing a PEM file containing the server certificate
    maxLength: 5000
    type: string
  client_certificate_file:
    description: A File ID representing a PEM file containing the client certificate
    maxLength: 5000
    type: string
  private_key_file:
    description: A File ID representing a PEM file containing the client RSA private key
    maxLength: 5000
    type: string
  private_key_file_password:
    description: Password for the private key file
    maxLength: 5000
    type: string
  ssid:
    description: Name of the WiFi network
    maxLength: 5000
    type: string
required:
  - client_certificate_file
  - private_key_file
  - ssid
title: TerminalConfigurationConfigurationResourceEnterpriseTLSWifi
type: object
x-expandableFields: []
